### PR TITLE
Highlighting Next Friend in client

### PR DESCRIPTION
**Pull request by PaxRomain**
I was looking through the code and I realized what causes the client to highlight a target is the "ChangeCombatant" packet. Under the original code, it checks if the target is a friend, and if so, will not send this packet and will also not change razor's record of the current combatant.

I added an option under the friends sub-tab to override this. If checked, razor sends the packet anyways, causing the friend to be highlighted in the client, but does not make any change to razor's current combatant. Though "ChangeCombatant" sounds vaguely hostile, I have played around with this and I can see no downside to sending this to the client for cycling through friends.

Quick, I am also a noob and this is my first github pull so I probably goofed some stuff but whatever.

### CODE REVIEW

**Comment by markdwags** [comment]
If you use ChangeCombatant on a friend, you are telling the server that you are attacking that target. I'd have to test, but I'd expect you to then be swinging fists/weapons if you stand next to a friend, no?

**Comment by PaxRomain** [comment]
Nope. Despite the name, it does not attack the target. If it did, anytime you cycled a non-friendly target Razor would be sending that packet and you would be attacking them (which would be bad, since you don't necessarily want to attack, just have them as a target). The only thing it does is highlight the target. The only really important part of the code is changing razor's record of combatant (the m_combatant), which you don't want it to do if the target is a friend.

Also, Steam highlights friend targets in the client. I'm assuming because it sends ChangeCombatant to the client like it does for all other next targets.

**Comment by markdwags** [comment]
I'll take a quick look at ClassicUO and RunUO and see what is actually happening. ChangeCombatant is just what the Razor folks called this packet years ago.

One UO packet guide calls it "Allow/Refuse Attack". Another one says "This tells the client which target they are fighting." so it sounds like you may be right. 

Let me confirm.  Thanks for the info.

**Comment by markdwags** [comment]
Since this PR had a ton of changes in the history from the deletion of files, the form auto-gen code reformatted -- was easier to just patch in your changes and just close this one out.  Thank you!

**Pull request closed without merging**
